e2e/framework/test_context.go
In case the state was saved before complete initialization of infrastructure (as state is saved in batches, with the first being as soon as any state is available), the state might not reflect the actual number of nodes provisioned - always override number of nodes from configuration if available.
=> Prioritize configuration when restoring state

e2e/framework/framework.go, e2e/framework/test_context.go
Failure to collecting OpsCenter logs should not prevent CoreDump from collecting install and/or agent logs.
=> Collect installer/agent logs even w/o service login configured

e2e/framework/framework.go, e2e/framework/test_context.go, infra/infra.go, infra/terraform/terraform.go, infra/vagrant/vagrant.go
Avoid using INSTALLER_URL as a wizard mode detector - do not remove from configuration environment, and determine if a provisioner should select an installer node only during infrastructure boostrapping.
=> Avoid using INSTALLER_URL as a wizard mode detector

infra/terraform/terraform.go
terraform: use SSH key from configuration before falling back to state configuration.
=> terraform: use SSH key from configuration before falling back to state

Makefile
minor changes, we don't actually have or use a v1.x branch for anything -- robotest detects and works with all versions
=> cleanup make, add what-version target

Makefile
Target "vendor" needs to be phony to work - otherwise, it will use vendor directory as a source of truth and the first build will fail.
=> Target "vendor" needs to be phony

suite/sanity/sanity.go
Alter test sets slightly, both to indicate cycles + nodes separately, and also to allow different size clusters individually.
=> slightly altered test sets

assets/terraform/azure/bootstrap/centos.sh, infra/gravity/provision.go
Enable eth0 in trusted zone for firewalld so multiple nodes can communicate
=> Enable eth0 in trusted zone for firewalld

assets/terraform/azure/bootstrap/centos.sh, infra/gravity/node_commands.go, lib/constants/constants.go
Query docker device on the host and store in gravity environment file to be able to override the installer command line. Environment: azure/redhat/centos.
TODO: I want to use a later opportunity to clean up some of this code - including moving install command into a proper text template.
=> azure: query docker device on host for redhat/centos

docker/Makefile, docker/suite/run_suite.sh, infra/gravity/cluster_install.go, infra/gravity/cluster_resize.go, infra/gravity/node_commands.go, lib/defaults/defaults.go, suite/sanity/loss_recover.go, suite/sanity/resize.go, suite/sanity/sanity.go, suite/suite_test.go
It can be provided in test json configuration dictionary, e.g.:
```
resize={"nodes":2,"to":3,"flavor":"two","state_dir":"/var/lib/gravity3"}
```
I'm planning to change one of existing gravity tests to use custom state dir so we don't have a separate test case just for this.
Also, fix robotest build - it was broken on my machine b/c docker was complaining that one of build args was unused.
=> Custom gravity dir support

.gitignore, assets/terraform/azure/bootstrap/centos.sh, assets/terraform/azure/node.tf, assets/terraform/azure/os.tf
workaround some occasionally happening issues:
- pin redhat 7.4 (version `7.4.2017111521` has some `iptables` issues due to default configs)
- static IP address allocation for nodes and essential config persistence to survive reboot
=> redhat / bootstrap fixes

assets/terraform/azure/bootstrap/centos.sh
Otherwise we will not be able to control ebtables rules from inside planet container.
=> Enable ebtables kernel module on newer kernels

e2e/framework/test_context.go, infra/terraform/config.go, infra/terraform/file_transfer.go
Because for air-gapped applications we should configure Iptables to drop all output traffic. It is impossible to do before downloading the installer, because download procedure will fail.
=> Execute post installer script

infra/gravity/node_commands.go
This change makes sure that the gravity binary from PATH is used to check gravity status. Before that some of the nodes were still using the old binary (from the installer package) to check for status.
This is needed for cases when after upgrade procedure the older gravity binary can no longer query the status from the new gravity-site due to some incompatibility. For example, it happened on my Trusted Clusters PR - GetOpsCenterLinks handler was removed and thus status was always failing on nodes that used the old binary.
With this change robotest passed on my PR:
```
[robotest] ******** TEST SUITE COMPLETED **********
[robotest] FAILED d1f1d4c-upgrade3lts4-1 {"role":"node","cluster":"","flavor":"three","remote_support":false,"state_dir":"/var/lib/gravity","os":{"Vendor":"redhat","Version" …
```
=> Use gravity from PATH when checking status

Makefile, infra/gravity/provision.go
I've been seeing a lot of resources left behind after multiple robotest runs. I think this happens when the initial bootstrapping fails for some reason and then the already expired provisioning context is used in a delete operation:
```
12:05:45 [robotest] time="2018-03-01T12:05:36Z" level=error msg="context timed out" 
12:05:45 [robotest] time="2018-03-01T12:05:36Z" level=error msg="context timed out" 
12:05:45 [robotest] time="2018-03-01T12:05:36Z" level=error msg="context timed out" 
12:05:45 [robotest] level=error msg="some nodes initialization failed, teardown this setup as non-usable" error="timed out" logs="https://goo.gl/GYyqsY" where=[/infra/gravity/provision.go:238] 
12:05:45 [robotest] level=error msg="VMs ready" elapsed=32m30.210463291s error="timed out, azureDestroy Delete …
```
=> Destroy resources using a fresh context.

assets/terraform/azure/bootstrap/centos.sh, assets/terraform/azure/bootstrap/ubuntu.sh, infra/gravity/parse.go, infra/gravity/parse_test.go, infra/gravity/provision.go
Relax `ParseDDOutput` to allow lose output (and avoid hiccups whenever "dd" is used with tools like sudo).
Map hostname to localhost in /etc/hosts to avoid
```
sudo: unable to resolve hostname
```
errors.
=> Relax "ParseDDOutput" to allow lose output

infra/gravity/cluster_install.go, infra/gravity/cluster_resize.go, infra/gravity/node_commands.go, infra/gravity/node_utils.go, infra/gravity/provision.go, lib/ssh/files.go, lib/ssh/time.go, lib/wait/retry.go
* Do not report non-final operation status as `trace.BadParameter` to avoid confusing the test retry loop [here](https://github.com/gravitational/robotest/blob/400cf792b151bb3c152433a3f2753eed2142e233/infra/gravity/testsuite.go#L197) and give the test the allotted number of retries in case of previous failures.
* Simplify lib/wait.Continue API to support formatting.
=> Do not abort test on non-final operation state

infra/gravity/node_commands.go, suite/sanity/install.go
* Allow passing installer URL via install parameters to override global one.
* Add support for `--ops-advertise-addr` install flag.
=> Add couple install parameters.

docker/suite/run_suite.sh
Expose the directories of corresponding `INSTALLER_URL` / `GRAVITY_URL` (i.e. keep old behavior) as docker volumes as opposed to exposing the file paths as this breaks the use-case of implicit `INSTALL_URL` override in a test that references a new file from the build directory.
=> Revert to old behavior for installer_url volume

infra/gravity/node_commands.go, lib/ssh/run_parse.go
This PR adds the option for robotest to run unattended updates for 5.4 (where the update mode has been flipped to be blocking by default).
This does not break other versions though as the blocking mode is controlled via an environment variable.
=> Run update unattended

infra/gravity/testsuite.go, lib/xlog/shorten.go
Remove shortening of log URLs as the service we were using was discontinued - return full URLs at the moment. This needs to be decided later whether to migrate to Firebase Dynamic Links (i.e. stay with google) or use other URL service or do completely away with shorterning.
=> Use full URLs for logs

assets/terraform/gce/bootstrap/ubuntu.sh, infra/terraform/terraform.go
Also bump number of retries for apt to `10`. Use `apt-get` instead of `apt` in the script.
=> Avoid robotest blocking on sub-process stdout/stderr on context expiration

assets/terraform/gce/bootstrap/ubuntu.sh, infra/gravity/terraform.go
* Bump teardown timeout to 20m.
* Fix ubuntu/debian bootstrap script to account for existing user.
=> Fix debian/ubuntu bootstrap w.r.t existing user

go.mod, go.sum
With the current gravitational/trace timestamp in the repo, I was seeing
the following error for most go operations in the Robotest repo:
$ go mod vendor
go: github.com/gravitational/trace@v0.0.0-20190626162700-a535a178675f: invalid pseudo-version: does not match version-control timestamp (2019-07-26T14:27:06Z)
I discovered this was because the timestamp in the go.mod/go.sum did not
match the timestamp on the following commit:
https://github.com/gravitational/trace/commit/a535a178675fb4a11ba74818491754a8c5575dd6
Correcting this addressed the issue for me.
Testing Done:
before
```
walt@work:~/git/robotest$ go mod vendor
go: github.com/gravitational/trace@v0.0.0-20190626162700-a535a178675f: invalid pseudo-version: does not match version-control timestamp (2019-07-26T14:27:06Z)
```
after: …
=> Fix corrupted go.mod/go.sum timestamp.

lib/system/file.go, lib/system/file_test.go
As I've been messing with robotest, I found a bug with copyall.  It contains logic for the src being a regular file, but will fail to create a directory -- unlike when the source was a directory.
This level of testing is probably overblown in the long run, but because I'm still learning go, I'm using these early patches as a playground to work on my skills.  Any and all feedback is appreciated... I don't know much/anything about go standards and conventions yet.
Testing Done:
See the tests added.  Here's the run before & after:
```
walt@work:~/git/robotest$ git checkout HEAD^
HEAD is now at 305e10d Add tests for the copyAll function.
walt@work:~/git/robotest$ go test ./lib/system       
--- FAIL: TestCopyAllFileDstAbsent (0.00s)
file_test.go:133: copy "/tmp/robotest-test138762263/src" -> …
```
=> Copyall fix

infra/gravity/config.go, infra/gravity/terraform.go, infra/terraform/config.go, infra/terraform/terraform.go, lib/constants/constants.go
Before this patch, robotest read terraform plugins from
/etc/terraform/plugins. /etc is only writeable by root so this became a
limiting factor preventing robotest dev environment setup without without
root privileges.
I recognize running robotest outside of its contianer is a somewhat
oblique use case, but it is something that both @bernardjkim and I
have found useful while getting started with the tool. In particular,
I find running outside containers useful for running robotest with
delve.
Testing done:
With the new setting:
```
walt@work:~/git/robotest$ ./debug.sh                 
+ dlv test ./suite -- -test.timeout=1h -gcl-project-id=redacted -test.parallel=1 -repeat=1 -fail-fast=true '-provision=
installer_url: telekube-6.3.6-linux-x86_64.tar
gravity_url: /home/walt/go/bin/gravity …
```
=> Make terraform plugin dir configurable.

suite/README.md, suite/sanity/sanity.go
Gravity 3 (where this name originated) is no longer supported, and this
test works with all supported gravity versions (5.x, 6.x, 7.x).  The
'3lts' affix is a vestigial quirk at this point.
This will require gravity CI scripts to update their syntax when they
migrate to a robotest version including this change.
The `upgrade3lts` name originated here, where it was changed from `upgrade`:
https://github.com/gravitational/robotest/commit/9bbf248dd124df62163812be1bd687f32e49b42b#diff-159fff6b77474dac6556f177cd277455R92
None yet.  But I'll rebase some of my other work on top of this and give it a shot.
=> Rename upgrade3lts to upgrade.

assets/terraform/gce/config.tf, docker/suite/run_suite.sh
As discussed in:
https://github.com/gravitational/gravity/commit/6d0e6b2141af41a0c3b86ce093120d4d9af42feb
https://github.com/gravitational/gravity/commit/7af1def4f624bfc2d7e7f5580fea399daa2921e6
Using GCE preemptible instances has not shown sufficient benefit.  As
such, Robotest will now default to using regular instances, and count on
consumers to enable preemption if they want to use it.
None yet.  I will post results once I've used this in some of my work on #189.
=> Turn off GCP preemptible instances by default.

infra/gravity/node_commands.go, suite/README.md
We have customers in the field that use the `--service-uid` and
`--service-gid` flags on their gravity clusters and are
reporting issues after upgrades related to these flags:
https://github.com/gravitational/gravity/issues/1279
Fixes #189.
[One node install test logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-26T00:57:55.032000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2225b8c851-a881-428f-9325-3e42399942bd%22%0Alabels.__suite__%3D%22350907b0-48ce-4810-98a0-b650f358d5ff%22%0Aseverity%3E%3DINFO&dateRangeStart=2020-03-25T23:57:55.472Z&dateRangeEnd=2020-03-26T00:57:55.472Z&interval=PT1H&scrollTimestamp=2020-03-26T00:39:15.409500178Z) …
=> Add service_uid and service_gid install params.

assets/terraform/gce/bootstrap/centos.sh, assets/terraform/gce/bootstrap/suse.sh, assets/terraform/gce/bootstrap/ubuntu.sh, infra/gravity/cluster_install.go
* Moves status query before the call to `uploadUpgrade` to counter recent test failures. `uploadUpgrade` only verifies the status in the cluster record and might fail due to an intermittent issue. This is not an ideal solution but might help avoid test failures.
* Removes state/etcd directories from the chowned list - these will be configured by the installer. The reason this is not done in the bootstrap script is that the script also runs on reboot and will break
the access to directories that aren't expected to be owned by the service user (which is especially critical with SELinux enabled).
=> A couple of tweaks

infra/gravity/node_commands.go
The k8s_config_url, pod_network_cidr, service_cidr, and license fields
were defined but undocumented and never used anywhere in
Robotest's code.  Setting them would have no effect.
I've chosen to remove these flags (instead of plumb them through)
because the testing necessary for plumbing them through is not presently
at the top of my priority list. Better to remove dead/unsupported code than
keep it around in hopes it may someday be useful.
The following run was done on a branch with these changes: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-25T21:11:57.234000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22ed3623f1-89c4-47d5-819c-a30e0 …
=> Remove unused InstallParams.

infra/gravity/node_commands.go
Older version of gravity try to read `/var/lib/gravity/local/gravity.db`
with the current user.  When these files are owned by someone other than
the current user (i.e. the system_uid/system_gid parameters are set)
`gravity status` will always fail with:
open /var/lib/gravity/local/gravity.db: permission denied
We avoid these permission problems by using sudo to run gravity (which
is consistent with all other executions of gravity in node_commands.go).
Fixes #194.
Before this change: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-26T23:27:47.848000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-03-26T22:28:13.863Z&interval=PT1H&scrollTimestamp=2020-03-26T23:26:59.342140371Z&advancedFilt …
=> Use sudo when querying post-operation status.

infra/terraform/terraform.go, infra/terraform/terraform_test.go, suite/README.md
This is a maintainer Quality of Life change.
These two parameters were previously handled as cli flags. This meant we
had two paths for routing data, and more annoyingly: it wasn't easy to
recreate a robotest `terraform apply` or `terraform destroy` via the
command line because these two values needed to be manually specified in
addition to the other values that came from robotest.tfvars.json.
* Internal change (not necessarily or a new feature)
N/A.  
When I have a development run leak resources, and I try to manually clean up, I will navigate to the terraform directory and run `terraform destroy`.  This previously resulted in the following prompt:
```
walt@work:~/git/robotest/logs/0504-1616/walt/install-1/ubuntu18/overlay2/1n/tf$ terraform destroy -var-file robotest.tfvars.json
var.os …
```
=> Pass `os` and `nodes` via robotest.tfvars.json.

assets/terraform/gce/node.tf
This change adds the "robotest" label to all intances and disks that robotest provisions in GCP.  This is primarily to help track billing of these resources, though it may also be useful for leak tracking & housekeeping purposes.
* New feature (non-breaking change which adds functionality)
* This change has a user-facing impact
Contributes to https://github.com/gravitational/robotest/issues/164
The  additional resources that we may want to track are:
1) stackdriver logs
2) bigquery entries
3) networks & subnetworks (not currently dynamically provisioned on GCP -- we recycle the same set over & over)
None of these codepaths were substantively similar, so I did not attempt to group them with this change.
I ran a single node install, and then manually re-ran the provision & destroy: …
=> Add GCP "robotest" label

suite/sanity/loss_recover.go
This PR contains minor cleanup necessary to run the formerly defunct `recover` test case, which was unofficially deprecated/broken by the work in #134 .
* Bug fix (non-breaking change which fixes an issue)
* Regression fix (non-breaking change which fixes a regression)
* Contributes to https://github.com/gravitational/robotest/issues/188
Before this test case would always fail with `trace.BadParameterError unknown OS vendor: ""` as seen [here](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-05T06:22:16.581000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2214f4bf5d-41b8-451e-b2fa-369dbad319b5%22%0Alabels.__suite__%3D%224ead932c-cd7f-4a13-922a-c4368 …
=> shrink research

.golangci.yml, infra/gravity/provision.go, infra/gravity/testsuite.go, infra/infra.go
This PR causes `make lint` to enforce `goimports` compatibility.
After the discussion at https://github.com/gravitational/robotest/pull/209#discussion_r419988351 I want to automate review that a machine can take care of so that I don't waste human reviewer time on it.
* Internal change (not necessarily a bug fix or a new feature)
* This change has a developer-facing impact
* Contributes to https://github.com/gravitational/robotest/issues/171
Before the 2nd commit:
```
walt@work:~/git/robotest$ make lint        
docker build --pull --tag robotest:buildbox \
--build-arg UID=$(id -u) \
--build-arg GID=$(id -g) \
--build-arg GOLANGCI_LINT_VER=1.21.0 \
docker/build
// snip ...
Successfully built fdb1bf1a6b37
Successfully tagged robotest:buildbox
docker run --rm=true -u $(id -u):$(id -g) -v …
```
=> Import lint

suite/sanity/sanity.go
I made a mistake when I removed the ability to specify upgrade tests
via upgrade3lts in c0540aa9bae1c8ad49fc61fd0e541b018bdd0c37.
The new 'upgrade' syntax is cleaner, but we've seen multiple occasions
where consumers of robotest fail to update the syntax at the same time
as they update robotest:
- https://github.com/gravitational/gravity/issues/1315
- https://github.com/gravitational/gravity/issues/1508
Lets be kind to robotest consumers and support both options for a
period. We can then remove the `upgrade3lts` syntax later when we're
more confident nothing is still using it.
```
+ dlv test ./suite -- -test.timeout=1h -gcl-project-id=<redacted> -test.parallel=1 -repeat=1 -fail-fast=true -always-collect-logs=true -resourcegroup-file=/home/walt/git/robotest/logs/0506-2131/alloc.txt …
```
=> Allow `upgrade3lts` as an alternative form of `upgrade`.

infra/gravity/testcontext.go, suite/suite_test.go
With #206 merged and version/commit information available within the go runtime, I now want to make sure that this info is recorded & accessible for all robotest runs.
Immediately, this is motivated by trying & failing to RCA https://github.com/gravitational/robotest/issues/214#issuecomment-625551626
I'd love to be able to make sure I'm running the exact same version.  I recognize this pach won't help with #214 because the cause predates all the version work.  But maybe it'll help me next time.
Via the console:
```
+ dlv test ./suite -- -test.timeout=1h -gcl-project-id=<redacted> -test.parallel=1 -repeat=1 -fail-fast=true -always-collect-logs=true -resourcegroup-file=/home/walt/git/robotest/logs/0507-1831/alloc.txt -destroy-on-success=true -destroy-on-failure=true -tag=walt -suite=sanity …
```
=> Add version & commit information to logs.

assets/terraform/gce/bootstrap/centos.sh
Disable epel repository to minimize access failures during `yum update` encountered frequently during bootstrapping a node.
Although I attempted to research the reason for the access failure:
```
yum install -y chrony python unzip
One of the configured repositories failed (Unknown),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:
1. Contact the upstream for the repository and get them to fix the problem.
2. Reconfigure the baseurl/etc. for the repository, to point to a working
upstream. This is most often useful if you are using a newer
distribution release than is supported by the repository (and the
packages for the previous distribution release still work).
3. Run the command with the …
```
=> Disable the epel repository to minimize bootstrap failures

infra/gravity/cluster_status.go, infra/gravity/terraform.go
This patch addresses a pet annoyance of mine. During cleanup on a failed
robotest run, the "Fetching node logs" logging statements show up as
errors when in reality they're running to completion as expected.
I also refactored logic surrounding the handling of apiserver logging to
clarify intent.  The special treatment of the first item of a was
confusing without the additional context that the first item was the
kubernetes api-server.
[Logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-12T01:45:00.684000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22d6e7b0ba-489d-457f-a10a-64d582a2c290%22%0Alabels.__suite__%3D%228a8f3ac0-dc17-44cc-ac91-7c2bd35 …
=> Switch fetch severity from ERR -> INFO.

version.sh
As discussed at:
https://github.com/golang/go/issues/32945
https://semver.org/#is-v123-a-semantic-version
Go and semver disagree about handling of a leading 'v' on version
strings.  This patch allows robotest to play nicely with both.
I discovered this when I created the v2.0.0-alpha.1 tag in git.
Contributes to https://github.com/gravitational/robotest/issues/200.
Before:
```
walt@work:~/git/robotest$ git describe --tags
v2.0.0-alpha.1
walt@work:~/git/robotest$ make version       
version metadata saved to version.go
Robotest Version: v2.0.0-alpha.1
```
After:
```
walt@work:~/git/robotest$ git describe --tags        
v2.0.0-alpha.1-1-g4ac1444
walt@work:~/git/robotest$ make version       
version metadata saved to version.go
Robotest Version: 2.0.0-alpha.1.1+4ac14441
```
With a …
=> Strip leading 'v' from git tags if present.

Makefile, docker/Makefile
Previously, `make publish` would unconditionally tag images with the version
*and another* tag, 'latest' if unspecified by the user.
In an effort to reduce the use of floating tags and encourage pinned use
of semantic versions, the build will now skip publishing a 2nd tag unless it
is specified by user/automation calling `make publish`.
This helps us move the TAG parameter in jenkins from a ChoiceParameter that must
have a default to a StringParameter that may be empty.  This should balance the need
for freeform tags (create whatever you want) with official build tags (it is no longer
necessary to create/update a 2nd tag if you don't need it) nicely.
Contributes to #200.
I found this when I changed the TAG parameter in the jenkins job to be a string, (default empty) and got the following …
=> Conditionally push an extra quay.io image tag.

docker/Makefile
Robotest-e2e has not been used for the duration of my tenure.
This can be seen in the quay.io usage logs, particularly the pulls:
https://quay.io/repository/gravitational/robotest-e2e?tab=logs
https://quay.io/repository/gravitational/robotest-suite?tab=logs
As nothing is reading this data, we don't need to push e2e releases
to quay.io until we find priority to address https://github.com/gravitational/robotest/issues/162.
This will speed up build & publish times and result in less quay.io
storage.
As far as I'm aware, the robotest-e2e images are unuseable due to Gravity UI changes (anyone know the bug/issue for this?) & a lack of priority to fix them. Additionally, with an increasing rate of robotest change, there are almost certainly significant regressions in e2e we haven't caught …
=> Disable publishing robotest-e2e quay.io images.

docker/e2e/Dockerfile, docker/suite/Dockerfile
Without this contemporary docker complains:
```
[WARNING]: Empty continuation line found in:
RUN  ...
[WARNING]: Empty continuation lines will become errors in a future release.
```
As discussed in https://github.com/moby/moby/pull/24725
Before:
<details><summary><code>make -C docker e2e suite VERSION=testing</code></summary>
<pre>
walt@work:~/git/robotest$ make -C docker e2e suite VERSION=testing
make: Entering directory '/home/walt/git/robotest/docker'
if [ -z ""/tmp/tmp.zBJaAeB5lU"" ]; then \
echo "TEMPDIR is not set"; exit 1; \
fi;
mkdir -p "/tmp/tmp.zBJaAeB5lU"/build
cp -r ../assets/terraform "/tmp/tmp.zBJaAeB5lU"
cp -a ../build/robotest-e2e "/tmp/tmp.zBJaAeB5lU"/build/
cp -r e2e/* "/tmp/tmp.zBJaAeB5lU"/
if [ "e2e" = "e2e" ]; then \
cd "/tmp/tmp.zBJaAeB5lU" && docker build …
=> Suppress docker continuation warnings.

docker/suite/run_suite.sh, infra/gravity/testsuite.go, suite/suite_test.go
While debugging, I frequently want to run a test once, with no option
for robotest to re-attempt it if/when it fails.  When robotest auto
retries, I must then abort the program and clean up the resources from
the next attempt. Previously, to do this I needed to edit
lib/defaults/defaults.go.
I explored an alternative implementation where `"attempts":3"` was an optional test parameter, e.g.:
```
'install={"attempts":3,"nodes":1,"flavor":"one","os":"redhat:7","storage_driver":"overlay2","role":"node"}'
```
I liked that this allowed per test retry configuration, but the impmentation had a couple downsides:
1) it was considerably more invasive
2) it raised difficult questions about configuration hierarchy.  Specifically of the above keys:
* attempts
is configuration outside the test
* nodes
* …
=> Add '-retries' cli flag.

Makefile, docker/Makefile
Without this `publish` was failing to pull, and `containers` was failing to
pass along the version and tag information.
After:
<details><summary>make containers</summary>
<pre>
walt@work:~/git/robotest$ make containers
docker build --pull --tag robotest:buildbox \
--build-arg UID=$(id -u) \
--build-arg GID=$(id -g) \
--build-arg GOLANGCI_LINT_VER=1.21.0 \
docker/build
Sending build context to Docker daemon  3.072kB
Step 1/12 : FROM quay.io/gravitational/debian-venti:go1.12.9-stretch
go1.12.9-stretch: Pulling from gravitational/debian-venti
Digest: sha256:0fea800bbea53134644b9d4a52bdcec433cbcb7ab3a8530279c0e4373b3a5cb4
Status: Image is up to date for quay.io/gravitational/debian-venti:go1.12.9-stretch
---> 273a8ecbe1d9
Step 2/12 : ARG UID
---> Using cache
---> 85e54c5ce85a
Step 3/12 : ARG …
=> Consistently add flags to recursive make targets.

infra/gravity/cluster_resize.go, suite/README.md, suite/sanity/install.go, suite/sanity/loss_recover.go, suite/sanity/sanity.go, suite/sanity/shrink.go
Fixes #188.
I also refactored RemoveNode -> RemoveNodes for signature consistency
with Expand() and the unused ShrinkLeave().
5.5.40 [shrink logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-22T02:37:23.621000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%225b9df45e-f63f-47f5-babb-2f881dfb4b1f%22%0Alabels.__suite__%3D%227b42a0e3-9bce-42ce-82b1-c608492facb3%22%0Aseverity%3E%3DINFO&dateRangeStart=2020-05-22T01:37:24.121Z&dateRangeEnd=2020-05-22T02:37:24.121Z&interval=PT1H&scrollTimestamp=2020-05-22T02:37:04.145726434Z)
7.0.5 [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timesta …
=> Add a shrink test scenario.

infra/gravity/testsuite.go
This may have negative consequences if anything is searching BigQuery
for PANICED, but there haven't been any recent queries, and are only 31
records with this status overall.
I will update the old records once this merges
```
walt@work:~/git/robotest$ make test > /dev/null && make lint > /dev/null; echo $?
0
```
=> Typo PANICED -> PANICKED.

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
These changes bring robotest in alignment with what Gravity offers and
expects from potential community contributors.
While this isn't specifically release docs, it is some prep work for the
release documentation I'm working on for #200. 
Eyeballed the changes here:
https://github.com/wadells/robotest/tree/contributing
=> Update README. Add CONTRIBUTING and CODE_OF_CONDUCT.

.github/pull_request_template.md
This will help maintainers & reviewers assess benefit and risk of future pull requests.
- Non-product change 
Contributes to #200.
This PR is the testing done. :smile: 
The template is largely copied from Robotest's Gravity mothership:
https://github.com/gravitational/gravity/blob/2a15a272262254b49a924fbd51d8b7bd98f60697/.github/pull_request_template.md
However, I've chosen to rework "Type of change" into the semver focused
"Risk Profile" as I want to be crisp about Robotest's versioning. I also
struck TODOs and Implementation as "to process heavy" after observing
how they're used (or not) in Gravity. Furthermore, I made "Related Issues"
optional, as Robotest doesn't see many ports or densely related issues
compared to Gravity.
=> Add a Pull Request template.

go.mod, infra/gravity/cluster_install.go, infra/gravity/cluster_resize.go, infra/gravity/cluster_status.go, infra/gravity/defaults.go, infra/gravity/gravity_test.go, infra/gravity/node_commands.go, infra/gravity/testcontext.go, infra/gravity/testdata/status-degraded-1641.json, lib/constants/constants.go, lib/defaults/defaults.go, suite/sanity/autoscale.go, suite/sanity/install.go, suite/sanity/loss_recover.go, suite/sanity/resize.go, suite/sanity/shrink.go, suite/sanity/upgrade.go
This change introduces more rigorous status checking in all suite tests cases.  Specifically, we go from `state != degraded` (30m timeout) to `state = active && system_status = Running` (5m timeout).
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
* Internal change (not necessarily a bug fix or a new feature)
I mention breaking because the 30m -> 5m timeout may break some of the tests cases we don't run presently.  It should be safe for all currently run test cases, because they wait for operations to complete before querying status.
Fixes #225.
Heavily rewrites the code introduced in #136.
Manual testing
Added unit tests for status validations. 
Logs from end-to-end runs:
* [upgrade](https://console.cloud.google.com/logs/viewer?advancedFi …
=> Check for "active" status

Makefile, go.mod, infra/gravity/cluster_install.go, infra/gravity/defaults.go, infra/gravity/testcontext.go, lib/config/config.go, lib/config/config_test.go, lib/config/duration.go, lib/config/duration_test.go, suite/sanity/install.go
Previously, ExecScript shared a 30m timeout with the status query loop.
Now, it can be specified by the user, or defaults to 5m if it is left
unspecified.
This is followup from https://github.com/gravitational/robotest/pull/233#discussion_r432104739
I'm not aware of *any* current use of the script install parameter. As such I'm tempted to remove the script capability entirely instead of adding ~125 SLOC to support it in a proper fashion.  This would be a breaking change that would require a semver major version bump (maybe merge before 2.0.0?).  The implementation in this PR falls under a minor version bump, as it adds a new configuration parameter for something previously unconfigurable.
With a 60s script and no timeout specified (thus the default):
```
walt@work:~/git/robotest$ …
```
=> Refactor ExecScript timeout to be user specified.

.github/pull_request_template.md
As discussed at:
https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab
GitHub flavored markdown requires a blank line after the summary tag
closes before it will properly start interpreting other html or
markdown.  Without this, `<p>` tags are injected into the `<pre>` block.
- Non-product change 
Fixes a display bug from #239 
<details><summary>without the space</summary>
<pre>
walt@work:~/git/robotest$ git status
On branch pr-template-fix
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
modified:   .github/pull_request_template.md
Untracked files:
(use "git add <file>..." to include in what will be committed)
foo
</pre>
</details>
<details><summary>with the space</summary>
<pre>
walt@work:~/git/robotest$ git status
On branch pr-template-fix …
=> Add a semantic newline to <details> in PR template

.github/pull_request_template.md, CONTRIBUTING.md, README.md, RELEASE.md
This PR captures the process I followed for the last two Robotest releases, and formally establishes expectations that the maintainers :
1) assess semver risk when new releases are put out
2) formally tag releases
Before, releasing and backwards compatibility was "best effort" and undocumented, contributing to failures like https://github.com/gravitational/gravity/issues/1508.
- Non-product change 
Fixes #200.
This documentation should help prevent issues like https://github.com/gravitational/gravity/issues/1508
I released the following two released following this process:
https://github.com/gravitational/robotest/releases/tag/v2.0.0-rc.1
https://github.com/gravitational/robotest/releases/tag/v2.0.0
I also eyeballed the docs and checked most links at: …
=> Establish a release process

infra/terraform/terraform.go
In logrus 1.0.3 (PR #237) all log fields started being escaped.  This multiline
terraform stdout was collapsed into a single line, and became quite
unreadable as described in #244.
To counteract this, put the stdout into the log message, instead of one
of the fields.  A bit of a hack, but it keeps console logs a bit more
readable
Although this "fixes" a regression, it doesn't restore the previous fuctionality exactly, just close enough for everyday uses.  This is more of a "fail forward" approach, as I didn't want to get locked on logrus 1.0.2 for eternity.
Fixes #244.
<details><summary>one node install console logs</summary>
<pre>
walt@work:~/git/robotest$ ./cfg/base.sh
version metadata saved to version.go
Robotest Version: …
=> Refactor terraform stdout logging.

assets/terraform/gce/bootstrap/centos.sh, assets/terraform/gce/bootstrap/suse.sh, assets/terraform/gce/bootstrap/ubuntu.sh, infra/gravity/provision.go
When awaiting for bootstrap script to complete, take a failed bootstrap state file into account to fail faster.
Fixes https://github.com/gravitational/robotest/issues/218.
Haven't done any testing yet.
=> Break out of bootstrap wait loop on failure

assets/terraform/gce/bootstrap/suse.sh, assets/terraform/gce/config.tf, assets/terraform/gce/node.tf
This PR includes necessary changes to run robotest against SUSE 15 sp1.
Although gravity doesn't support this distribution yet, this work will come in handy when we want to add SUSE 15 support to Gravity (and thus validate it with robotest).
See the individual commit messages for more context on the two changes.
Contributes to #248 and gravitational/gravity#1582.
Logs [here](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-06-15T18:25:05.442000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2227d33712-3515-48a6-835e-c51dbf8d8091%22%0Alabels.__suite__%3D%22afa7468d-fd1b-4f43-8ace-206e2f28d4dd%22&dateRange …
=> Bootstrap script SUSE 15 support

suite/sanity/install.go, suite/sanity/loss_recover.go, suite/sanity/resize.go, suite/sanity/sanity.go, suite/sanity/shrink.go, suite/sanity/upgrade.go, suite/suite_test.go
In order to accommodate unique installers on a per test basis always treat the `InstallerURL` from the provisioner as the default and override it when `installer_url` is specified in the test parameter JSON. This was previously available for the install test, but is now available for all tests in the sanity suite.
This is needed to spit the images between upgrade and all other testing
for incremental rollout of new robotest images:
* https://github.com/gravitational/gravity/issues/1908
* https://github.com/gravitational/gravity/issues/1915
<details><summary>install without overide</summary>
```
walt@work:~/git/robotest$ dlv test ./suite -- -test.timeout=1h -gcl-project-id=redacted -test.parallel=1 -retries=1 -fail-fast=true …
```
=> Refactor InstallerURL config passing.

infra/gravity/gravity_test.go, infra/gravity/node_commands.go, infra/gravity/testdata/status-active-5.0.36.json, infra/gravity/testdata/status-degraded-5.0.36.json
This PR fixes a Gravity 5.0.x compatiblity regression introduced by https://github.com/gravitational/robotest/pull/233.  Specifically, when trying to parse the output of `gravity status --output=json` on 5.0.36 robotest would fail with the following error: `json: cannot unmarshal string into Go struct field`.
- Bug fix (patch release)
Fixes #247.
See the unit tests added.  Here is what it looks like to run them:
<details><summary><code>go test ./infra/gravity</code> before the second commit</summary>
```
walt@work:~/git/robotest$ go test ./infra/gravity/
--- FAIL: TestGravity5036ActiveStatusValidation (0.00s)
gravity_test.go:127: 
Error Trace:    gravity_test.go:127
Error:          Received unexpected error:
json: cannot unmarshal string into Go struct field …
```
=> Properly parse Gravity 5.0.36 status

infra/gravity/testsuite.go, lib/xlog/all_test.go, lib/xlog/shorten.go
This PR includes a logging fix when the robotest container is running from a GCP node, plus some test case refactoring I did along the route to diagnosing and understanding the issue.
- Bug fix (patch release)
Fixes #265 
I published robotest-suite:2.2.0-alpha.0.6-5f438094 and used that from an upcoming gravity branch on a gcp instance:
<details><summary><code>make -C build.assets/robotest run</code></summary>
```
walt@gcp:~/git/gravity$ make -C build.assets/robotest run                                                                                                                                     
make: Entering directory '/home/walt/git/gravity/build.assets/robotest'
make -j /home/walt/git/gravity/build/current/robotest/images/robotest-7.0.7.tar …
```
=> Fix log links when run from GCP nodes & opportunistic cleanups

infra/gravity/loglink_test.go, infra/gravity/testsuite.go
This new log link format provides two benefits:
* The links now have a timestamp, meaning the view will jump to the
relevant window, instead of requiring the user to scroll back in time
from the moment they clicked the link.
* [Google Logs Viewer has a new considerably nicer UI](https://cloud.google.com/logging/docs/view/logs-viewer-preview).  The new link
navigates directly to this new UI.
- New feature or internal change (minor release)
N/A
Here is a link generated from a noop test run:
https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%2231993e89-276e-4e21-9ac8-df8433ef9da5%22%0Alabels.__suite__%3D%2214204050-f630-436c-8b68-d95e1877d915%22;timeRange=2020-09-23T16:05:42Z%2F2020-09-23T17:05:42Z?project=kubeadm-167321
```
walt@work:~/git/robotest$ go …
```
=> Update GCP log link format.

assets/terraform/gce/bootstrap/centos.sh, assets/terraform/gce/os.tf
This changeset includes several fixes/improvements to RHEL and CentOS testing:
* Bootstrap is fixed for 8.x (no longer depends on `python` in path, ensures `semanage` before use, remove deprecated sysctl)
* Updated images
* Minor versions (7.8, 8.2) are provided, for greater specificity during testing.
- New feature or internal change (minor release)
* Fixes https://github.com/gravitational/robotest/issues/258
* Fixes https://github.com/gravitational/robotest/issues/256
* Developed as part of https://github.com/gravitational/gravity/pull/2203 
All below are 1 node installs with gravity 5.5.52
* [CentOS 8.2](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%224c928278-d561-4cec-ab4d-c9e4ce7924b7%22%0Alabels.__suite__%3D%22c139a11b-50ce-4df8-970a-41a57 …
=> CentOS & Redhat 8 fixes

assets/terraform/gce/os.tf
This change adds the ability to test Gravity on CentOS/RHEL 7.9 and 8.3.  Customers have asked for this.
* Contributes to https://github.com/gravitational/gravity/issues/2331
* [CentOS 7.9 x Gravity 7.0.25](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%2279ef7556-5966-41e0-aa71-6453b081cfb2%22%0Alabels.__suite__%3D%22c4d1195c-3f68-4a0c-8191-b1853e158f1a%22;timeRange=2020-11-13T23:24:44Z%2F2020-11-14T00:24:44Z?project=kubeadm-167321)
* [RHEL 7.9 x Gravity 7.0.25](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%22ff29db0d-b288-4557-a4e4-7c807632ba97%22%0Alabels.__suite__%3D%22c4d1195c-3f68-4a0c-8191-b1853e158f1a%22;timeRange=2020-11-13T23:24:44Z%2F2020-11-14 …
=> Add CentOS/RHEL 7.9 and 8.3 to distros offered.

.drone.yml, Makefile, RELEASE.md, docker/Makefile, suite/README.md, version.sh
This patch introduces code & documentation changes to move the robotest release flow from Jenkins to Drone CI.
- New feature or internal change (minor release)
N/A
I tagged and released 2.3.0-alpha.1 off this branch:
https://drone.gravitational.io/gravitational/robotest/61
https://quay.io/repository/gravitational/robotest-suite?tag=latest&tab=tags
There appears to be about a 10% difference in image size -- I suspect this is due to some old base images cached in Jenkins.  The new image size is consistent with what I get when I build locally.
For the version.sh changes:
<details><summary><code>make version</code></summary>
```
$ make version
version metadata saved to version.go
Robotest Version: 2.3.0-alpha.1.1+582636d8
walt@work:~/git/robotest$ git tag -d $(git tag -l)
Deleted tag '0.0.1' …
```
=> Add Release to Drone CI

assets/terraform/gce/bootstrap/centos.sh, assets/terraform/gce/bootstrap/sles.sh, assets/terraform/gce/bootstrap/ubuntu.sh
This avoids the need to install python or use pip to install v1 of the AWS cli.  This recently became important because after https://github.com/pypa/pip/pull/9189, pip no longer runs with many distros default python 2.7 resulting in failures like #279.
- Bug fix (patch release)
* Fixes #279 
See the following automates runs:
* [sles 12-sp5](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%22647bedb6-d141-4bfb-90cd-3173022e267a%22%0Alabels.__suite__%3D%22afbedaaa-b62c-45e9-8ee9-e85a85447b1f%22;timeRange=2021-01-27T03:43:49Z%2F2021-01-27T04:43:49Z?project=kubeadm-167321)
* [ubuntu 18.04](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%223d7d4650-13ea-4915-b49e-578d50525aed%22%0Alabels.__suite__%3D%22afbedaaa- …
=> Install awscli without python/pip

assets/terraform/gce/bootstrap/centos.sh
The epel and gcloud repos have been a consistent source of failures
during the bootstrap execution -- typicially due to changes in infrastructure
outside of Gravitational's control.  As we don't need packages from either
of these repos for Robotest, we can nuke them before attempting any yum
operations they could disrupt.
- New feature or internal change (minor release)
* Mitigates https://github.com/gravitational/robotest/issues/282 and https://github.com/gravitational/robotest/issues/214
Centos 7, 8, RHEL 7, 8 all tested here:
https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__suite__%3D%22827ba907-aaec-4bdf-9077-b38fd1727de1%22;timeRange=2021-04-01T19:57:05Z%2F2021-04-01T20:57:05Z?project=kubeadm-167321
=> Remove epel and gcloud rpm repos

assets/terraform/gce/os.tf
Like the title says!
* https://github.com/gravitational/gravity/issues/2563
3 node upgrade from 8.0.0-apha.0 to 9.0.0-beta.2: https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%2294aeba7e-c495-4ac2-aeea-b7c23dbc826a%22%0Alabels.__suite__%3D%221162a757-f510-47de-b6a0-692225f76ad9%22;timeRange=2021-07-20T21:39:51Z%2F2021-07-20T22:39:51Z?project=robotest-production
I also did a one node install on 7.0.33, but my cloud logging config was broken that run, so I can't point to the logs.
CentOS has switchted from long lived releases to "centos-stream": https://www.centos.org/centos-stream/
However the image I grabbed happens to align with 8.4:
```console
[centos@robotest-6bfbb7a9-node-0 ~]$ cat /etc/*-release …
```
=> Add RHEL/CentOS 8.4 to supported distros

Makefile, docker/build/Dockerfile, go.mod
This also required removing the `go test -i` flag, which has been
deprecated, as it no longer provides any useful value:
https://golang.org/doc/go1.16#i-flag
N/A
<details><summary><code>make build</code></summary>
```
walt@aws:~/git/robotest$ git checkout go-1.16
Switched to branch 'go-1.16'
walt@aws:~/git/robotest$ make build
version metadata saved to version.go
docker build  --tag robotest:buildbox \
--build-arg UID=$(id -u) \
--build-arg GID=$(id -g) \
--build-arg GOLANGCI_LINT_VER=1.32.2 \
--iidfile /home/walt/git/robotest/build/.robotest-buildbox.iid \
docker/build
Sending build context to Docker daemon  3.584kB
Step 1/12 : FROM quay.io/gravitational/debian-venti:go1.16.6-buster
---> 28677cb1de3c
Step 2/12 : ARG UID
---> Using cache …
```
=> Upgrade go to 1.16
