- e2e/model/ui/defaults/defaults.go
Some applications take longer to install.
> allow longer installation

- infra/wizard.go
- lib/wait/retry.go
quiet logging around retries a bit
> lower some logging around retries

- e2e/framework/test_context.go
- e2e/framework/test_state.go
- e2e/model/ui/bandwagon.go
- e2e/model/ui/defaults/defaults.go
- e2e/specs/asserts/bandwagon/bandwagon.go
- e2e/specs/aws_install.go
- e2e/specs/onprem_install.go
Add support for other bandwagon fields, if they exist. Also support configuring values for them.
> support more and configurable bandwagon fields

- e2e/framework/applications.go
- e2e/framework/framework.go
- e2e/specs/applications.go
- e2e/specs/onprem_site.go
- e2e/specs/site.go
- e2e/update_test.go
- infra/infra.go
- infra/terraform/terraform.go
- infra/update.go
- infra/vagrant/vagrant.go
Implementation real update with:
* executing `upload` script from installer
* upgrade app via web
> Application upgrade test

- e2e/framework/framework.go
- e2e/framework/test_context.go
Closes https://github.com/gravitational/gravity/issues/2036
> Add a mode to only provision a cluster

- docker/Dockerfile
- docker/entrypoint.sh
- e2e/framework/framework.go
Withoun enabled capabilities latest chrome(58, maybe 57 too) crashes inside docker container.
> Run chromedriver inside container

- docker/entrypoint.sh
Also with exec command no need to redirect streams.
> Add quotes for command line params

- infra/config.go
Fixes https://github.com/gravitational/gravity/issues/2239
> Fix the JSON tag on InstanceType.

- infra/terraform/config.go
this is a temporary fix to unblock the guys.
> temporary quick fix

- assets/terraform/azure/bootstrap/centos.sh
https://github.com/gravitational/gravity/issues/2730
> config firewall before install

- assets/terraform/azure/node.tf
- assets/terraform/azure/os.tf
- docker/suite/run_suite.sh
- infra/gravity/cluster_install.go
- infra/gravity/config.go
- infra/gravity/defaults.go
- infra/gravity/provision.go
- infra/gravity/terraform.go
- infra/gravity/testcontext.go
- infra/gravity/testsuite.go
- lib/constants/constants.go
- lib/defaults/defaults.go
- suite/suite_test.go
waits for installer to be ready to parallel jenkins pipeline
> os versions and wait for installer

- e2e/uimodel/bandwagon/bandwagon.go
- e2e/uimodel/installer/installer.go
Add sleep after entering new site page.
> Add filling of organization field

- infra/gravity/cluster_install.go
- infra/gravity/node_commands.go
- lib/defaults/defaults.go
- lib/ssh/commands.go
- suite/README.md
- suite/sanity/install.go
- test.sh
fixes https://github.com/gravitational/gravity/issues/3003
> support custom script post installer transfer

- e2e/framework/test_context.go
- e2e/onprem_test.go
- e2e/uimodel/user/login.go
> Add check for login page is loaded. Add some logging.

- assets/terraform/azure/os.tf
Add Centos 7.4 SKU (stock keeping unit) and update azure Centos 7.4 version
> Add CentOS 7.4 on azure

- infra/gravity/node_commands.go
- lib/ssh/scp.go
Don't forget to close stdin after copying - otherwise the receiver will hang forever.
> Don't forget to close stdin after copying

- infra/gravity/provision.go
Otherwise, the VMs (and corresponding resources) will be left behind if any of the following has failed:
- bootstrap script
- post-provisioning (i.e. clock sync)
- disk requirement check
> Destroy resources explicitly if provisioning fails.

- infra/gravity/testsuite.go
- lib/xlog/google_cloud_log.go
Update the resource type to 'project' (was 'global') as this changed.
It is currently unclear why and when exactly this change took place.
> Update the resource type to `project`

- infra/gravity/cluster_status.go
It is not guaranteed that the first node is always a master node.
This changes the behavior of always using the first node to query node roles by selecting the apiserver node.
> Use a master node (apiserver) to initially group nodes by roles.

- infra/gravity/node_commands.go
- lib/constants/constants.go
Fixes https://github.com/gravitational/robotest/issues/201.
I will validate the change manually before merging.
> Add SELinux triggers for SELinux-enabled hosts

- infra/gravity/cluster_status.go
- infra/gravity/node_commands.go
- lib/constants/constants.go
These are a couple minor items I factored out of my shrink work in #229.  See the individual commit messages for more context.
7.0.5 [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-20T05:02:13.690000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22e1dbcb40-c486-40a5-b294-4f8578d0db80%22%0Alabels.__suite__%3D%22188d1189-da74-47d8-89c0-3a4ed268ea08%22%0Aseverity%3E%3DINFO&dateRangeStart=2020-05-20T03:39:51.336Z&interval=PT1H&scrollTimestamp=2020-05-20T04:47:53.927326441Z&dateRangeUnbound=forwardInTime)
> Miscallaneous cleanup.

- assets/terraform/gce/bootstrap/suse.sh
- infra/gravity/node_logs.go
This is the first part of my work to allow Robotest to exercise SUSE.  This PR has a MVP for running robotest install against SUSE 12 sp15.
Contributes to https://github.com/gravitational/robotest/issues/248 and https://github.com/gravitational/gravity/issues/1582.
The following runs were all run from this branch:
- [install](https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2291b451ab-d1f1-49bb-b1a8-366a81fe95a9%22%0Alabels.__suite__%3D%22d7b8d877-ab8c-4cd0-93fd-062af7857c1f%22%0Aseverity%3E%3DINFO&authuser=1&expandAll=false&project=kubeadm-167321)
- [expand](https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2279f690b3- …
> MVP work to exercise SUSE

- assets/terraform/gce/bootstrap/suse.sh
- assets/terraform/gce/os.tf
This updates our SUSE images and fixes two small issues I found while testing the new images.
Fixes a minor bug introduced in #253 when the root partition already uses all available space.
SUSE 12 [logs](https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2259d64e43-be85-4941-964b-1498a1c4ffeb%22%0Alabels.__suite__%3D%2274b4b74f-b29c-40df-961d-7d897fe1e7a3%22%0Aseverity%3E%3DINFO&authuser=1&expandAll=false&project=kubeadm-167321)
SUSE 15 [logs](https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%226ee5199c-08c8-46b2-a629-56e7799855da%22%0Alabels.__suite__%3D%2274b4b74f-b29c-40df-961d-7d897fe1e7a3%22%0Aseverity%3E%3DINFO&auth …
> Update SUSE images.

- assets/terraform/gce/os.tf
This PR updates debian 9 and 10 images.
- Bug fix (patch release)
#291 
https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%2284af73d5-882b-4acf-9828-2b94e6890d25%22%0Alabels.__suite__%3D%222800a6e4-cbf0-4521-96a8-191b6a85aed6%22;timeRange=2021-08-24T22:13:09Z%2F2021-08-24T23:13:09Z?project=robotest-production
> Update debian images
